name: "Setup Packwiz"
description: "Install Go and packwiz for modpack management"

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "stable"

    - name: Install packwiz
      shell: bash
      run: |
        go install github.com/packwiz/packwiz@latest
        echo "$HOME/go/bin" >> $GITHUB_PATH

        echo "Installed packwiz successfully"
        echo "Packwiz version: $(go version -m $(which packwiz) | head -n 3 | tail -n 1 | awk '{print $3}')"
