name = "layer_1"
author = "zer0cell"
version = "0.3.3-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "737c91b98ffec5a931d6fe7e3b62d0a2b5bb6ed9d1c2881a46c0f9d13bfcdf52"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "config/openloader/data"
