name = "layer_1"
author = "mannie-exe"
version = "0.4.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78789e408021bbc82e634a131a7f116eaa521e30ce61c4447a1b43801d07301d"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "config/openloader/data"
