name = "layer_1"
author = "zer0cell"
version = "0.2.2-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ad96d49d192aca72c3a515827475c68eb5c27ae21e6861c56b7fd1e44e02042"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "config/openloader/data"
