name = "layer_1"
author = "zer0cell"
version = "0.2.1-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5b9a0f438b3e54492e1fc062364aa97e9c9cb7310893ee438824663735cc4804"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "config/openloader/data"
