name: Validate Pack

on:
  pull_request:
    paths:
      - 'pack/**'
      - 'empack'
      - 'man'
      - '.github/workflows/validate.yml'
  workflow_dispatch:

jobs:
  validate:
    name: Validate Modpack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup empack Environment
        uses: ./.github/actions/setup-empack

      - name: List all mods
        run: ./man list:mods

      - name: List client-side mods
        run: ./man list:mods:client

      - name: List server-side mods
        run: ./man list:mods:server
