name: Validate Pack

on:
  pull_request:
    paths:
      - 'pack/**'
      - 'make.sh'
      - '.github/workflows/validate.yml'
  workflow_dispatch:

jobs:
  validate:
    name: Validate Modpack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Packwiz Environment
        uses: ./.github/actions/setup-packwiz

      - name: Refresh pack index
        run: packwiz --pack-file pack/pack.toml refresh

      - name: List all mods
        run: |
          echo "## All Mods"
          packwiz --pack-file pack/pack.toml list

      - name: List client-side mods
        run: |
          echo "## Client-side Mods"
          packwiz --pack-file pack/pack.toml list --side client

      - name: List server-side mods
        run: |
          echo "## Server-side Mods"
          packwiz --pack-file pack/pack.toml list --side server
